
<form class="" action="<?php echo $block->getBaseUrl().'articles/index/save'; ?>" id="smartosc-articles-form" method="post">
    <fieldset class="fieldset">
        <legend class="legend"><span>Test Form For Smastosc Articles Module</span></legend><br>
        <div class="field note no-label">Write here anything you want.</div>
        <div class="field title">
            <label class="label" for="title"><span>Title</span></label>
            <div class="control">
                <input name="title" id="title" title="Name" value="" class="input-text" type="text">
            </div>
        </div>
        <div class="field content">
            <label class="label" for="content"><span>Content</span></label>
            <div class="control">
                <textarea name="content" id="content" title="Content" class="input-text" cols="5" rows="3"></textarea>
            </div>
        </div>
        <div class="field author">
            <label class="label" for="image"><span>Image</span></label>
            <div class="control">
                <input name="image" id="image" title="Image" value="" class="input-text" type="text">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>